name: Postman API Testing CI

on: push

jobs:
  newman-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # CÀI NEWMAN & REPORTER ---
      - name: Install Newman and HTML Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # TẠO THƯ MỤC REPORT ---
      - name: Create Report Directory
        run: mkdir -p test-results

      - name: Run Postman Collection
        run: |
          newman run https://api.postman.com/collections/23338478-ec65b058-b645-45df-bbba-003d19760957? \
          -e https://api.postman.com/environments/23338478-2a366c60-06d6-4bda-97ce-b74c07521185? \
          -r cli,htmlextra \
          --reporter-htmlextra-export test-results/html-report.html \
          --reporter-htmlextra-title "API Test Report"

      #  UPLOAD BÁO CÁO
      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-html-report
          path: test-results/
          retention-days: 30 # Giữ báo cáo trong 30 ngày
